src/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name='update'),
    url(r'(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='details'),
    url(r'$', ItemListView.as_view(), name='list'),

]

src/profiles/urls.py
from .views import ProfileDetailView

from django.conf.urls import url

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name="detail")
]

src/menus/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from restaurants.models import RestaurantLocation

class Item(models.Model):
    # associations
    user            = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant      = models.ForeignKey(RestaurantLocation)
    
    # item stuff
    name            = models.CharField(max_length=120)
    contents        = models.TextField(help_text='separate each item by comma')
    excludes        = models.TextField(blank=True, null=True, help_text='Separate each item by comma')
    public          = models.BooleanField(default=True)
    image_url       = models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menus:details', kwargs={'pk': self.pk})

    # Defines the meta data of the model
    class Meta:
        ordering = ['-updated', '-timestamp'] #Item.objects.all()

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

src/profiles/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save

User = settings.AUTH_USER_MODEL

class ProfileManager(models.Manager):
    def toggle_follow(self, request_user, username_to_toggle):
        profile_ = Profile.objects.get(user__username__iexact=username_to_toggle)
        user = request_user
        is_following = False
        if user in profile_.followers.all():
            profile_.followers.remove(user)
        else:
            profile_.followers.add(user)
            is_following = True
        return profile_, is_following


class Profile(models.Model):
    user            = models.OneToOneField(User) #user.profile
    followers       = models.ManyToManyField(User, related_name='is_following', blank=True)
    # following       = models.ManyToManyField(User, related_name='following', blank=True)
    activated       = models.BooleanField(default=False)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    objects         = ProfileManager()

    def __str__(self):
        return self.user.username

def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        profile, is_created = Profile.objects.get_or_create(user=instance)
        
        # Adding a default follower
        # Targets user with id = 1 
        default_user_profile = Profile.objects.get_or_create(user__id=1)[0] #Alternative user__username
        
        # Adds the newly created user as a follower of the user with id = 1
        default_user_profile.followers.add(instance)

        # Adding followers to the new user
        # Adding user with id = 1 to the 
        profile.followers.add(default_user_profile.user)
        profile.followers.add(2)

post_save.connect(post_save_user_receiver, sender=User)

src/profiles/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import DetailView, View

from profiles.models import Profile
from menus.models import Item
from restaurants.models import RestaurantLocation

User = get_user_model()

class ProfileFollowToggle(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        username_to_toggle = request.POST.get("username")
        profile_, is_following = Profile.objects.toggle_follow(request.user, username_to_toggle)        
        return redirect(f"/u/{profile_.user.username}/")

class ProfileDetailView(DetailView):
    template_name = 'profiles/user.html'

    def get_object(self):
        username = self.kwargs.get("username")
        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(*args, **kwargs)
        user = context['user']

        is_following = False
        if user.profile in self.request.user.is_following.all():
            is_following = True
        
        context['is_following'] = is_following

        query = self.request.GET.get('q')

        items_exists = Item.objects.filter(user=user).exists()
        qs = RestaurantLocation.objects.filter(owner=user).search(query)

        if items_exists and qs.exists():
            context['locations'] = qs
        return context

src/profiles/templates/profiles/user.html
{% extends "base.html" %}

{% block head_title %} {{ user.username }} || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>{{ user.username }}</h1>
<p>{% include 'profiles/snippets/follow_form.html' with username=user.username is_following=is_following %}</p>

<form class='form' method='GET' action='.'>
    <input type='text' placeholder='Search...' name='q' value='{{ request.GET.q }}'> 
    <button class='btn btn-default' type='submit'>Search</button>
</form>
<hr/>
{% if locations %}
    {% for obj in locations %}
    <div class='row'>
        <div class='col-sm-12'>
            <div class='thumbnail'> 
                <h3>{{ obj.title }}</h3> 
                <p>
                    <a href='{{ request.path }}?q={{ obj.location }}'>{{ obj.location }}</a> | 
                    <a href='{{ request.path }}?q={{ obj.category }}'>{{ obj.category }}</a>
                </p>
                <p>
                    <ul>
                        {% for item in obj.item_set.all %}
                            <li style='margin-bottom: 10px'><b>{{ item.name }}</b><br/> 
                                {% for ing in item.get_contents %}
                                    <a href='{{ request.path }}?q={{ing}}'>{{ ing }}</a>
                                {% endfor %}
                            </li>
                        {% endfor %}
                    </ul>
                </p>
                <hr/>
            </div>
        </div>
    </div>
    {% endfor %}
{% else %}
    <p class='lead'>No Items Found</p>
{% endif %}

{% endblock %}