src/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name='update'),
    url(r'(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='details'),
    url(r'$', ItemListView.as_view(), name='list'),

]

src/muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView

from menus.views import HomeView
from profiles.views import ProfileFollowToggle

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name="follow"),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurant')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name="about"),
    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name="contact"),
]

src/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

src/templates/snippets/form_snippet.html
<form method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<div class="container">
    <h1>MuyPicky.com</h1>
    <a href='{% url "home" %}'>Home</a>
    <a href='{% url "about" %}'>About</a>
    <a href='{% url "contact" %}'>Contact</a>
    {% if request.user.is_authenticated  %}
    <a href='{% url "restaurant:list" %}'>Restaurants</a>
    <a href='{% url "menus:list" %}'>Menu Items</a>
    {% endif %}
</div>

src/templates/snippets/sidebar.html
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
</ul>